title: Saurabh Purohit blog
description: About me
url: "https://purohit10saurabh.github.io"
baseurl: ""

permalink: /:title/

theme: minima

header_pages:
  - index.md
  - life.md

markdown: kramdown
kramdown:
  math_engine: null

show_excerpts: true
excerpt_separator: "<!--more-->"

sass:
  quiet_deps: true

github_username: purohit10saurabh
twitter_username: purohit10saurab
